USE WebPhotoShare
GO
INSERT INTO collections VALUES
('Animals', 1,  ''),
('Architecture', 1,  ''),
('Art', 1,  ''),
('Cars &amp; Motorcycles', 1,  ''),
('Celebrities', 1,  ''),
('Design', 1,  ''),
('DIY &amp; Crafts', 1,  ''),
('Education', 1,  ''),
('Film, Music &amp; Books', 1,  ''),
('Food &amp; Drink', 1,  ''),
('Gardening', 1,  ''),
('Geek', 1,  ''),
('Hair &amp; Beauty', 1,  ''),
('Health &amp; Fitness', 1,  ''),
('History', 1,  ''),
('Holidays &amp; Events', 1,  ''),
('Home Decor', 1,  ''),
('Humor', 1,  ''),
('Illustrations &amp; Posters', 1,  ''),
('Kids', 1,  ''),
('Men''s Fashion', 1,  ''),
('Outdoors', 1,  ''),
('Photography', 1,  ''),
('Products', 1,  ''),
('Quotes', 1,  ''),
('Science &amp; Nature', 1,  ''),
('Sports', 1,  ''),
('Tattoos', 1,  ''),
('Technology', 1,  ''),
('Travel', 1,  ''),
('Weddings', 1,  ''),
('Women''s Fashion', 1,  '')